Traceback (most recent call last):
  File "manage.py", line 10, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 16, in main
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Watching for file changes with StatReloader
* Owlready2 * Warning: optimized Cython parser module 'owlready2_optimized' is not available, defaulting to slower Python implementation
/usr/local/lib/python3.7/dist-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
[04/Nov/2020 10:16:56] "GET / HTTP/1.1" 200 30631
Not Found: /favicon.ico
[04/Nov/2020 10:17:04] "GET /favicon.ico HTTP/1.1" 404 2598
Internal Server Error: /result/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/charlesxavia/diabetes-project/DiabetesDiagnosisProject/DiabetesDiagnosisProject/views.py", line 42, in diagnose
    data = main("?id", "=", ":{}".format(patientID))
  File "/home/charlesxavia/diabetes-project/DiabetesDiagnosisProject/DiabetesDiagnosisProject/fetchData.py", line 72, in main
    results = getData(graph, request)
  File "/home/charlesxavia/diabetes-project/DiabetesDiagnosisProject/DiabetesDiagnosisProject/fetchData.py", line 33, in getData
    results = list(graph.query(request))
  File "/usr/local/lib/python3.7/dist-packages/rdflib/graph.py", line 1127, in query
    result = plugin.get(result, query.Result)
  File "/usr/local/lib/python3.7/dist-packages/rdflib/plugin.py", line 107, in get
    return p.getClass()
  File "/usr/local/lib/python3.7/dist-packages/rdflib/plugin.py", line 69, in getClass
    module = __import__(self.module_path, globals(), locals(), [""])
  File "/usr/local/lib/python3.7/dist-packages/rdflib/plugins/sparql/__init__.py", line 37, in <module>
    from .processor import prepareQuery, processUpdate
  File "/usr/local/lib/python3.7/dist-packages/rdflib/plugins/sparql/processor.py", line 18, in <module>
    from rdflib.plugins.sparql.evaluate import evalQuery
  File "/usr/local/lib/python3.7/dist-packages/rdflib/plugins/sparql/evaluate.py", line 20, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
[04/Nov/2020 10:17:20] "POST /result/ HTTP/1.1" 500 124964
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
November 04, 2020 - 10:15:22
Django version 3.1.3, using settings 'DiabetesDiagnosisProject.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
* Owlready2 * Warning: optimized Cython parser module 'owlready2_optimized' is not available, defaulting to slower Python implementation
/usr/local/lib/python3.7/dist-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Internal Server Error: /result/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/charlesxavia/diabetes-project/DiabetesDiagnosisProject/DiabetesDiagnosisProject/views.py", line 47, in diagnose
    ddmodel = joblib.load(os.path.join(settings.BASE_DIR, 'DDiag_model.pkl'))
  File "/usr/local/lib/python3.7/dist-packages/joblib/numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/local/lib/python3.7/dist-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python3.7/pickle.py", line 1085, in load
    dispatch[key[0]](self)
  File "/usr/lib/python3.7/pickle.py", line 1373, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python3.7/pickle.py", line 1423, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'sklearn.tree._classes'
[04/Nov/2020 10:18:42] "POST /result/ HTTP/1.1" 500 84960
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
November 04, 2020 - 10:18:31
Django version 3.1.3, using settings 'DiabetesDiagnosisProject.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
* Owlready2 * Warning: optimized Cython parser module 'owlready2_optimized' is not available, defaulting to slower Python implementation
/usr/local/lib/python3.7/dist-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Internal Server Error: /result/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/charlesxavia/diabetes-project/DiabetesDiagnosisProject/DiabetesDiagnosisProject/views.py", line 47, in diagnose
    ddmodel = joblib.load(os.path.join(settings.BASE_DIR, 'DDiag_model.pkl'))
  File "/usr/local/lib/python3.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 598, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 526, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python3.7/pickle.py", line 1085, in load
    dispatch[key[0]](self)
  File "/usr/lib/python3.7/pickle.py", line 1373, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python3.7/pickle.py", line 1423, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'sklearn.tree._classes'
[04/Nov/2020 11:12:56] "POST /result/ HTTP/1.1" 500 85232
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
November 04, 2020 - 11:12:44
Django version 3.1.3, using settings 'DiabetesDiagnosisProject.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
* Owlready2 * Warning: optimized Cython parser module 'owlready2_optimized' is not available, defaulting to slower Python implementation
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/usr/local/lib/python3.7/dist-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.7/dist-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.7/dist-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.7/dist-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/dist-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/dist-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/charlesxavia/diabetes-project/DiabetesDiagnosisProject/DiabetesDiagnosisProject/urls.py", line 18, in <module>
    from .views import *
  File "/home/charlesxavia/diabetes-project/DiabetesDiagnosisProject/DiabetesDiagnosisProject/views.py", line 20, in <module>
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib' from 'sklearn.externals' (/usr/local/lib/python3.7/dist-packages/sklearn/externals/__init__.py)

Performing system checks...

